export interface Infos {
    id: string,
    fname: string,
    mname: string,
    lname: string,
    extname: string,
    empnumber: string,
    email: string,
    cnumber: string,
    gender: string,
    address: string,
    age: string,
    mstatus: string,
    datebirth: string,
    placebirth: string,
    department: string,
    designation: string,
    salary: string,
    datestarted: string,
    education: string,
    contact: string,
    contactperson: string,
    relationship: string,
    sss: string,
    pagibig: string,
    tin: string,
    phealth: string,
    sched: string,
    dependencies: string,
    maidenname: string,
    branch: string,
    lastupdated: string,
}
export interface EvaluatedList {
    id: string,
    ratername: string,
    raterposition: string,
    purpose: string,
    rateefname: string,
    rateemname: string,
    rateelname: string,
    rateeenum: string,
    rateeposition: string,
    datehired: string,
    dateevaluated: string,
    attendance: string,
    workefficiency: string,
    behavior: string,
    tattendance: string,
    tworkefficiency: string,
    tbehavior: string,
    totalscore: string,
    comment: string,
}

export interface Schedule {
    id: string,
    fname: string,
    mname: string,
    lname: string,
    year: string,
    month: string,
    monthyear: string,
    monthyear2: string,
    monthNumber: string,
    shift: string,
    day1:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
    day2:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
    day3:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
    day4:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
    day5:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
    day6:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
    day7:{
        day: string,
        label: string,
        duty: string,
        color: string,
        text: string,
        timestart: string,
        timeend: string,
        timestart12: string,
        timeend12: string,
        time: string,
    },
}
export interface payroll{
        id: string,
        fname: string,
        mname: string,
        lname: string,
        extname: string,
        position: string,
        email: string,
        status: string,
        empnumber: string,
        basicpay: number,
        period: string,
        year: string,
        month: string,
        pym: string,
        otregular: number,
        otnightdiff: number,
        nightdiff: string,
        nightdifftotal: number,
        totalUT: number,
        totalUTrate: number,
        totalOT: number,
        thmonth: number,
        incentives: number,
        paidleaves: number,
        holidaypay: number,
        otheradd: number,
        allowance: number,
        hourrate: number,

        adjustment: number,
        overtime: number,
        deduction: number,  
        
        whtax: number,
        sss: number,
        phealth: number,
        pagibig: number,
        tardiness: number,
        loan: number,
        otherdeduction: number,
        salaryloan: number,
        calamityloan: number,
        
        grosspay: number,
        netpay: number,

        date1: string,
        timein1: string,
        timeout1: string,
        thour1: string,
        totalOT1: string,
        totalUT1: string,
        holiday1: string,
        holidayrate1: string,
        undertime: string,
}

export interface payslip{
    id: string,
    id2: string,
    fname: string,
    mname: string,
    lname: string,
    extname: string,
    position: string,
    email: string,
    status: string,
    empnumber: string,
    basicpay: number,
    period: string,
    year: string,
    month: string,
    pym: string,
    otregular: number,
    otnightdiff: number,
    nightdiff: string,
    nightdifftotal: number,
    totalUT: number,
    totalUTrate: number,
    totalOT: number,
    thmonth: number,
    incentives: number,
    paidleaves: number,
    holidaypay: number,
    otheradd: number,
    allowance: number,
    hourrate: number,
    adlnytdiff: number,
    adlnytdiff2: number,

    adjustment: number,
    overtime: number,
    deduction: number,  
    
    whtax: number,
    sss: number,
    phealth: number,
    pagibig: number,
    tardiness: number,
    loan: number,
    otherdeduction: number,
    salaryloan: number,
    calamityloan: number,
    
    grosspay: number,
    netpay: number,

    date1: string,
    timein1: string,
    timeout1: string,
    thour1: string,
    totalOT1: string,
    totalUT1: string,
    holiday1: string,
    holidayrate1: string,
    undertime: string,
    totalnyt: string,
}